name: MiniPixel SMP
version: '${project.version}'
main: online.minipixel.smp.Main
api-version: 1.17
authors: [ AAWA ]
description: minipixel smp plugin
website: minipixel.online

commands:
  afk:
    permission: minipixel.smp.commands.afk
    description: AFK command for the smp server

  help:
    permission: minipixel.smp.commands.help
    description: help command for smp server
