name: MiniPixel-SMP
version: '${project.version}'
main: online.minipixel.smp.Main
api-version: 1.18
authors: [ AAWA ]
description: minipixel smp plugin
website: minipixel.online
dependencies: PlaceholderAPI

commands:

  menu:
    permission: minipixel.smp.commands.menu
    description: menu command for smp server

  backpack:
    permission: minipixel.smp.commands.backpack
    description: backpack command for smp server
    aliases:
      - bp
      - b

  team:
    permission: minipixel.smp.commands.team
    description: team command for the rang builder+

  warp:
    permission: minipixel.smp.commands.warp
    description: command for the smp warp system

  enderchest:
    permission: minipixel.smp.commands.ec
    description: command to open the enderchest
    aliases:
      - ec