name: smp-server
version: '${project.version}'
main: earth.aaronwagner.smp.Main
api-version: 1.19
authors: [ AAWA-byt ]
description: smp server plugin
website: aaronwagner.earth

commands:

  menu:
    permission: smp.commands.menu
    description: menu command for smp server

  backpack:
    permission: smp.commands.backpack
    description: backpack command for smp server
    aliases:
      - bp
      - b

  team:
    permission: smp.commands.team
    description: team command for the rang builder+

  warp:
    permission: smp.commands.warp
    description: command for the smp warp system

  enderchest:
    permission: smp.commands.ec
    description: command to open the enderchest
    aliases:
      - ec