name: MiniPixel SMP
version: '${project.version}'
main: online.minipixel.smp.Main
api-version: 1.18
authors: [ AAWA ]
description: minipixel smp plugin
website: minipixel.online
dependencies: PlaceholderAPI

commands:
  afk:
    permission: minipixel.smp.commands.afk
    description: AFK command for the smp server

  help:
    permission: minipixel.smp.commands.help
    description: help command for smp server

  menu:
    permission: minipixel.smp.commands.menu
    description: menu command for smp server

  backpack:
    permission: minipixel.smp.commands.backpack
    description: backpack command for smp server
    aliases:
      - bp
      - b

  vip:
    permission: minipixel.smp.commands.vip
    description: vip command for the rang vip, vip+, builder, supporter, developer and moderator

  team:
    permission: minipixel.smp.commands.team
    description: team command for the rang builder+

  warp:
    permission: minipixel.smp.commands.warp
    description: command for the smp warp system

  jda:
    permission: minipixel.smp.commands.jda
    description: command for the smp discord bot